<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML241ENSkillsNetwork31576874-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# Random Forests (RF) for classification with Python

Estimated time needed: **45** minutes

## Objectives

After completing this lab you will be able to:

*   Understand the difference between Bagging and Random Forest
*   Understand  that Random Forests have less Correlation between predictors in their ensemble, improving accuracy
*   Apply Random Forest
*   Understand Hyperparameters selection in  Random Forest

In this notebook, you will learn Random Forests (RF) for classification and Regression. Random Forest is similar to Bagging using multiple model versions and aggregating the ensemble of models to make a single prediction. RF uses an ensemble of tree’s and introduces randomness into each tree by randomly selecting a subset of the features for each node to split on. This makes the predictions of each tree uncorrelated, improving results when the models are aggregated. In this lab we will illustrate the sampling process of RF to Bagging, then demonstrate how each predictor for random forest are not correlated. Finally, we will apply Random Forests to several datasets using Grid-Search to find the optimum  Hyperparameters.

<h1>Table of contents</h1>

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ol>
        <li><a href="https://#RFvsBag">What's the difference between RF and Bagging </a></li>
        <li><a href="https://#Example">Cancer Data Example</li>
        <li><a href="https://practice/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML241ENSkillsNetwork31576874-2022-01-01">Practice</a></li>

</div>
<br>
<hr>

Let's first import the required libraries:

In [ ]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.3 numpy==1.21.2 ipywidgets==7.4.2 scipy==7.4.2 tqdm==4.62.3 matplotlib==3.5.0 seaborn==0.9.0
# Note: If your environment doesn't support "!mamba install", use "!pip install"

In [1]:
import pandas as pd
import pylab as plt
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt
from sklearn import metrics
from tqdm import tqdm

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/sklearn/utils/validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'

Ignore error warnings

In [2]:
import warnings
warnings.filterwarnings('ignore')

This function will calculate the accuracy of the training and testing data given a model.

In [72]:
def get_accuracy(X_train, X_test, y_train, y_test, model):
    return  {"test Accuracy":metrics.accuracy_score(y_test, model.predict(X_test)),"train Accuracy": metrics.accuracy_score(y_train, model.predict(X_train))}

This function calculates the average correlation between predictors and displays the pairwise correlation between  predictors.

In [4]:

def get_correlation(X_test, y_test,models):
    #This function calculates the average correlation between predictors  
    n_estimators=len(models.estimators_)
    prediction=np.zeros((y_test.shape[0],n_estimators))
    predictions=pd.DataFrame({'estimator '+str(n+1):[] for n in range(n_estimators)})
    
    for key,model in zip(predictions.keys(),models.estimators_):
        predictions[key]=model.predict(X_test.to_numpy())
    
    corr=predictions.corr()
    print("Average correlation between predictors: ", corr.mean().mean()-1/n_estimators)
    return corr

<h2 id="RFvsBag">  What's the difference between RF and Bagging </h2>

RF is similar to Bagging in that it uses model ensembles to make predictions. Like Bagging it if you add more models, RF does not suffer from Overfitting. In this section, we go over some of the differences between RF and Bagging, using the dataset:

### About the dataset

We will use a telecommunications dataset for predicting customer churn. This is a historical customer dataset where each row represents one customer. The data is relatively easy to understand, and you may uncover insights you can use immediately. Typically, it is less expensive to keep customers than acquire new ones, so the focus of this analysis is to predict the customers who will stay with the company.

This data set provides information to help you predict what behavior will help you to retain customers. You can analyze all relevant customer data and develop focused customer retention programs.

The dataset includes information about:

*   Customers who left within the last month – the column is called Churn
*   Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
*   Customer account information – how long they had been a customer, contract, payment method, paperless billing, monthly charges, and total charges
*   Demographic info about customers – gender, age range, and if they have partners and dependents

Load Data From CSV File

In [9]:
churn_df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv")

churn_df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0

In [14]:
churn_df.dtypes

tenure      float64
age         float64
address     float64
income      float64
ed          float64
employ      float64
equip       float64
callcard    float64
wireless    float64
churn         int64
dtype: object

### Data pre-processing and selection

Let's select some features for the modeling. Also, we change the target data type to be an integer, as it is a requirement by the skitlearn algorithm:

In [11]:
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip', 'callcard', 'wireless','churn']]
churn_df['churn'] = churn_df['churn'].astype('int')
churn_df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0

### Bootstrap Sampling

Bootstrap Sampling is a method that involves drawing of sample data repeatedly with replacement from a data source to estimate a model parameter. Scikit-learn has methods for Bagging but its helpful to understand Bootstrap sampling. We will import <code>resample</code>

In [15]:
from sklearn.utils import resample

Consider the five rows of data:

In [16]:
churn_df[0:5]

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0

We can perform a bootstrap sample using the function <code>resample</code>; we see the dataset is the same size, but some rows are repeated:

In [19]:
for n in range(5):

    display(resample(churn_df[0:5]))

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0

### Select Variables at Random

Like Bagging, RF uses an independent bootstrap sample from the training data. In addition, we select $m$ variables at random out of all $M$ possible
variables. Let's do an example.

In [20]:
X=churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']]

there are 7 features

In [21]:
M=X.shape[1]
M

7

Let us select $𝑚=3$, and randomly sample features from the 5 Bootstrap Samples from above.

In [22]:
m=3

We list out the index of the features

In [23]:
feature_index= range(M)
feature_index

range(0, 7)

We can use the function to sample to  randomly select indexes

In [24]:
import random
random.sample(feature_index,m)

[6, 1, 4]

We now randomly select features from the bootstrap samples, in randomly selecting a subset of the features for each node to split on.

In [28]:
for n in range(5):

    print("sample {}".format(n))
    display(resample(X[0:5]).iloc[:,random.sample(feature_index,m)])

sample 0

    ed  tenure  employ
4  2.0     7.0    15.0
4  2.0     7.0    15.0
2  1.0    23.0     2.0
4  2.0     7.0    15.0
4  2.0     7.0    15.0

sample 1

    ed  income  employ
3  2.0    76.0    10.0
2  1.0    30.0     2.0
1  2.0    33.0     0.0
1  2.0    33.0     0.0
2  1.0    30.0     2.0

sample 2

    age  employ  tenure
1  33.0     0.0    33.0
0  33.0     5.0    11.0
0  33.0     5.0    11.0
2  30.0     2.0    23.0
2  30.0     2.0    23.0

sample 3

    age   ed  equip
4  35.0  2.0    0.0
2  30.0  1.0    0.0
0  33.0  5.0    0.0
3  35.0  2.0    1.0
3  35.0  2.0    1.0

sample 4

    age  address  employ
1  33.0     12.0     0.0
4  35.0     14.0    15.0
1  33.0     12.0     0.0
0  33.0      7.0     5.0
2  30.0      9.0     2.0

In Random Forest, we would use these data subsets to train each node of a tree.

## Train/Test dataset

Let's define X, and y for our dataset:

In [29]:
y = churn_df['churn']
y.head()

0    1
1    1
2    0
3    0
4    0
Name: churn, dtype: int64

## Train/Test dataset

We split our dataset into train and test set:

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=1)
print ('Train set', X_train.shape,  y_train.shape)
print ('Test set', X_test.shape,  y_test.shape)

Train set (478, 9) (478,)
Test set (205, 9) (205,)

### Bagging  Review

In [31]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

Bagging improves models that suffer from overfitting; they do well on the training data, but they do not Generalize well. Decision Trees are a prime candidate for this reason, in addition, they are fast to train; We create a <code>BaggingClassifier</code> object,  with a Decision Tree as the <code>base_estimator</code>.

In [74]:
n_estimators=20
Bag= BaggingClassifier(base_estimator=DecisionTreeClassifier(criterion="entropy", max_depth = 4,random_state=2),n_estimators=n_estimators,random_state=0,bootstrap=True)

We fit the model:

In [37]:
Bag.max_samples

1.0

In [77]:
Bag.fit(X_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=2,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=20, n_jobs=None, oob_score=False,
         random_state=0, verbose=0, warm_start=False)

The method <code>predict</code> aggregates the predictions by voting:

In [38]:
Bag.predict(X_test).shape

(60,)

In [43]:
Bag.base_estimator

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=2,
            splitter='best')

In [44]:
Bag.n_features_

7

In [45]:
Bag.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=2087557356, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=132990059, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=1109697837, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=123230084, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=633163265, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=998640145, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=1452413565, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=2006313316, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=45050103, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=395371042, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=1587149235, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=191269509, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=237186348, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=1668685308, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=620267411, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=439259671, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=2140390242, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=963653404, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=1309320516, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=2137312669, splitter='best')]

In [46]:
Bag.estimators_samples_

[array([ 32,  64,  54,  41,  67,   1,  49,   7, 111,  39,  57, 102,  31,
         76, 139, 108, 103,  69,  48,  81,   3,  16, 101,  80, 126,  26,
        111,  32,  87,  89, 121,  54, 134,  38, 134, 114,  60,  16, 136,
         97, 119,   0,   9, 122,   1, 109, 111, 106, 105,  66, 129, 117,
         90,  47,  56,  88, 134, 126,  95, 111, 102,  97,  22,  45, 108,
         79,  47, 105, 115, 114,   1,  30,   4,  93,   3,  68,  20, 125,
         66,  56, 109,  93, 102, 139, 134, 133,  14,  22,  39,  61,  12,
        109,  79,  62,   5,  77,  17, 120,  24, 118, 102,  57, 135,  33,
         75,  65,  30,  59,  25, 120, 125, 122,  84,  49,  59,  25,  10,
         59,  49,  36,  16,  57, 112,  91,  90, 121, 105, 117, 100,  93,
         22, 132,   9, 116,  36,  74,  70,  55, 101,  23]),
 array([107,   0,  17,  39,  72,  13,  98,   7,  14, 110,  43,   9, 129,
         41,  85,  59,  61,  83,  20,  28,  93, 108,  46,  58, 122,  81,
         49,  84, 125, 127,  63, 120,  18, 121,  61,   0, 116,  75,  19,
        131,  71, 107,  55,   1, 108,  32,   8,  92,  70,  21,  82,  22,
          2, 138,  40,  73,  83,  46,  80, 138,  61,  21,  53,  10, 117,
        107,  63,  85,  76,  60,  42,  99,  28,  17,  28,  33,  45, 112,
         64,  55,  78,  27,  16,  36, 109,  81,   5,  59,  93,  95, 136,
         71,  57, 124,  36,  74,  78,  64, 129, 139,  50, 119,  76,  68,
         39,  93,  81,  97,  72,  89,  96,   2,  89,   7,  79,   6,  86,
         98, 129, 120,  54,  59,  34, 102, 115,  31, 107,  71,  77,  76,
        102,  13,  64,  53, 132, 119,  10,  62,  96,  28]),
 array([ 45,  51,  14,  69,  10,  55,  33,  23,  23,  88, 126,  55,  86,
         46,  48,  63, 137, 113, 102, 121,  94,  59,  19,  93,  92,   1,
          4,  23, 128,  63, 137,   3,  50,   3, 117, 122,  74,  48, 132,
         60,  65,  99,   7,  23,  63,  59,  89, 116, 118, 107,  99,  80,
        129,  21,  72,  71, 123,   7,  17, 129,  52,   2,   1, 133, 136,
         42, 128,  60,  28,  40,   9, 117, 108,   4, 102, 109,  49,  43,
        110,  23, 118, 104, 127,  85,  64,  16,  90,  47, 120, 138,  81,
         26, 110,   2, 125,  87, 114,  28,  82,  15,  98,  47,  39, 106,
          2, 139, 139,  13, 117,  42, 108,  17,   7,  69,  51,  32,  31,
         57,  58,  95,  36,  69, 137, 123,  26,  86,  17,  84,  66,  35,
         47,  51,  50,  16, 129,  83,  74,  70,  34,  13]),
 array([132, 101,  16,  88,   3, 112,  35,  28,  97, 105,  39,  85,   7,
         25,  59,  44,  21,  20,  37,   6,   7,  35, 132,  54,   1,  68,
         19,  42, 130,  53,   0,  91,  48,   8, 105, 122,  57, 116, 110,
         33,  59,  10,  13, 111,  63,  90,  51,  64, 127,  87,  88, 130,
         79,  57, 115,  36,  97, 128,  76,  42,  92,  98, 122,  88,  25,
         48,  60,  29,  52,  46, 138,  69,  71,  11, 106,  94, 131,  82,
         86, 132,  32, 128, 106,  28,  73,  99,  83, 113,  66,  57,   2,
         21,   9,  63, 103,  68,  43,  79,  55,  69, 106,  43,  51,  39,
        119, 120,  96,  75,  53,  69, 108,  57, 104, 122,  68,  82,  82,
        122, 108,  94,  63, 105,  35,   6, 136,  86,  97, 120,  62,  95,
        105, 128,  88,   4,  12,  14,  90,  11,  72,  69]),
 array([  1, 105,  11, 107,  11,  69, 111,  67,   6,  83,  68,  74, 103,
         28,  95,  98,  45,  66,  90, 115, 116,  52,  94,  52,  25, 102,
         35,  76,  33, 113,  12, 119,  42,   8,  53,  74,  20,   7,  74,
         28,  37,  59,   6,   0,  37,  35,  61,  22,  20, 111, 114,  89,
         12, 104,   9,  60,  41,  59,  67,  25,  87,  39,  73,  38,  91,
        134,  57, 129,  40,  92,  52,  62,  62, 118,  55, 115,  13,  64,
         56,  24,  21, 133,  79,  28,  96, 105, 105,  25,  77, 122,  60,
         68,  13,  83,  39,  89,  72,  51,  55,  71,  99,  18,  53,  85,
        123, 139,  68,   5,   5,  18,  79, 127,  67,   2,  77, 134,  75,
         14, 112,  86,   9,  21,  96, 126,  51,  77,  52,   7,  90,  46,
         15,  49,  38, 133, 118,  65,  66, 122,  85,   0]),
 array([ 17,  23, 119,   0,  49,  19,  90,  81,  93,  59,   0, 122,  63,
         89,  95,  54, 126, 136,  44, 107,   2,  24,  73,  34,  54, 107,
         97,  78, 122,  82,  81,  66,  98, 134,  75, 133,  50,   8,  28,
        135, 133, 117, 123,  37,  69, 115, 109,  31, 113,  59,  64,  59,
         90,  40,  90,  23,  34, 112,  71,  76, 103,  64,  54,  31, 114,
         36,  96,  28, 134, 100,   8,  28,   0, 122,  31,   4,  53,  88,
         68,  69,  59,  41,  45,  68,  26, 131, 114,  36,  45,  87,  21,
         53, 115,  94, 137,  29,   7,  55,  50,  75, 106,  34,  35, 118,
         35,  87,  72,   3,  37, 110,  39,  90,  22, 102,  62,   1,  88,
          3,  66,  75, 132,   7,  43,  39,  56,  23, 129,  43, 124,  57,
         59,  62,  35, 105,  70, 102, 128,  37, 117, 110]),
 array([125,  30, 126,  20,  85,  42,   4,  45,   7,  28,  42, 113, 109,
         80,  16, 102,   7,  25,  60, 110,  63,  73,   4,  90,  63, 130,
         55,  29,  45,  34, 131,   5,  71,  34,  98,  96,  36,  85, 100,
         79,  26, 105, 123,  19,  76,  88, 131,  39, 134, 106,  64, 132,
         96,  20, 126,  19,  77,  33, 125,  36,  95,  51,  77,  98,  26,
         49, 107,  51,  90, 135, 138,   2,  26,  58,  74,  62, 118, 104,
          6, 114, 128, 108, 136, 101, 110,  92,  91,  74,   9, 113,  58,
        113, 136,   6,   1,  66,  71,  30,  80, 136, 121,  28,  31, 139,
         92,  59, 101,  28, 100,  13, 106,  42, 125,  36, 129,   2, 125,
         56, 139,  83,  93,  32,  87,  78,   5, 127,  30,  38,  59, 122,
        133,   0, 119,  65, 131, 137,  14,  81,  99,  80]),
 array([100,  58,  10,  32,  25,  12,  30,   1,  73,  50,  20, 130, 133,
        120,  56,   5,  65, 134, 133,  36,  43, 101, 119,  95,  33,  23,
         45,  16,  91,   6,   1, 120,  28,  22, 100,  26,  32, 102, 128,
         11, 113,  40, 112, 120, 120,  53,  23,   9,  60,  77, 117,  63,
        127,  67,  63,  35,  67,  25,  60,   4,  87,  82,  28, 119,  85,
        130,  23,  51, 102, 124, 127, 131,  28, 131,  76,  60,  89, 129,
        112, 121,  13,  94, 107,  13, 121,  66,  81,  16,  93,  99, 128,
        118,  37,  83,  40,  89, 103,  38,  84,  69,   2,  72,   9,   2,
         30, 112, 123,  13,  71, 104, 104,   3, 131, 115,  28, 114,  85,
          2,  97,  18,  11,  47, 132,  15, 111,  46, 113,  97,  15,  80,
         91,  90,   8,  53,  24,  21,  13,   7, 126,  61]),
 array([ 10,  25, 107, 112,  52,  10,  73, 129,  20, 115,  44, 109, 132,
         35,  77, 112,  66,  24,  77,  35,  72, 117,  21,  66,  19,  85,
        125, 102,  72,  83,  53,  57,  15,  16,   1,  72, 130, 134,  79,
         75, 106, 137, 134,  32,  99,  27, 112,  32,  30, 124,  78,  66,
         11, 135,  18,  79, 128,  90,  81,  37, 102,  63,  59,  85,  15,
         28,  58,  33,  85, 106,  22, 119,  18,  14,  31,  28, 105,  97,
        106,  93, 127,  64,  91, 130,  19,  65, 120,  22, 129,  40, 136,
        115,  15,   2, 102,  90, 135,  26, 133, 122,  73,  51,  99,  41,
        120,  90, 119,  99,  44,  80, 123,  18, 115,   6,  99,  65, 133,
         79,  81, 124,  77,  97,  89,  46,  67, 101,  52,  52,  33,  12,
         96,  30,  58,  79,  83,  95, 100,  89,  95, 134]),
 array([ 34, 123,  99, 126, 116, 138,  77,  65,  95, 128,   7,  48,  17,
          1,  61,  64, 104,   0, 119, 114, 119,   4, 117,  20, 128,  60,
         26,  52,   8,  32,  23, 107,  37,  52, 115,  40, 113, 101,  44,
         44,  90, 130,  19,  28,  43, 107, 128, 134, 104,  13,   1,  91,
        114,  10,  60,  16,  64, 125, 123, 122,  69,  97,  62,  59,  59,
         15,  40,  35,  82,  22,  60,  33,  66,   2,  78,  99,  62, 104,
         76,  69,  14,  57,  36, 137,  45,  58,  86,  49, 114,  35,  55,
         40,  87,  59,  26,   3, 129,  39, 111,  52,  17,  35,  22,  31,
         31,  54, 102, 113,   7,  73,  20,  41,  17,  84, 116,  65,  64,
        132,  23, 132,  29,  26, 131,  42, 132,  26,  70,   8,  39,   4,
         67,  29,  63,  91, 127,  87, 104, 114,  19, 123]),
 array([ 59,  23, 115, 114,  57,  82,  50,  49,  68, 120,  92,  89,  51,
         68,  62, 138,  17,  21,  55, 126,  41, 118,  75,  39, 104,  92,
        124, 119,  96,  98,   4, 134,  91,  61,  43, 107,  83, 114,  27,
          4,  31,  70,  10, 118,  11,  61,  14,  76,  39, 128,  47,  29,
         87,  52, 133, 130,   1,  66,  13,  42, 109, 107, 101,  49,  81,
         14, 128, 138,  24, 122, 110,  55,  87,  65, 117,  17,  55,  40,
         32,  48,  82, 129,  48, 114,  90,  28,  84,  82,   7,  21,  38,
        118, 122,  31, 113, 109,  45,  23,  22,  56,  40,  25, 126,  74,
         31,  76, 100, 113,   0,   1,  37,  99,  78,  77, 135,  29, 114,
        138,  48, 127, 127, 113,  50,  13,   1,  27,  91,   0,  33, 126,
         43,  91, 136,   1,  72, 124, 122, 127,  20, 133]),
 array([133,  82,  37,  33,  73,  28,  17,  34, 107,  48,  76,  73, 128,
         99,   0, 105, 129,  14,  93,  73,   8,  26,  74,  93,  82, 138,
        115, 116, 120, 118,  46,  57, 138,  19,  36,  67, 105,  52,  80,
        136,   1,  63,  44, 119,  26,   8,  30,  96, 113, 105,  73, 130,
          3,  37, 102,  43,  39,  14,  85, 110, 133, 107,  99, 135,  59,
         22,  67, 126,  43,  56, 121, 127,  88,  19,  17,  12,  59, 130,
        138,  28,  84, 128,  18,  18,  70,  39,  19,  59, 101,  63,  60,
        137,   9,  14, 138, 117,  75, 101,  82,  60,  13, 102,  55,  10,
         47, 135,  44,  23,  76,  48,  60, 109,  90,  62, 130,   0,  89,
        113, 112,  91,  19,  83,  90,  89, 114, 129,  74,  28, 134,  92,
        104,  91, 103, 103,  40, 119,  20,   3, 132,  68]),
 array([ 44, 138,  71, 112,   3,  19,   7,  91,  38, 138,   9, 118, 123,
          6, 104, 113, 106,  41,   8,  67,   2, 135,  27, 115, 137,  46,
        128,  23, 122,  33,  69, 134, 106,  80, 139,  87,  73,  98,  79,
         18,  73,   5,  24,  78,  21, 120,  93,  65, 137,  20,  65,  62,
        111, 116,   7,  49,  77,  15,  80, 136,  87,  32,  72,  14, 112,
        114,  29,  44,   4,  68, 101,  48, 107,   2,  11,  65, 123,   5,
         22,  29,  93, 132, 131, 105,  60, 103,  43,  17, 127,  13, 136,
         25, 122,  45,  17, 122, 117,  23,  25,  93,  50,  62,  55, 119,
         33,  88,  53,  78, 117, 109, 126, 113,  79, 112,  17,  45, 106,
         61, 125,  46, 109, 127,  30,  26, 135,  17,  77,  86,  42, 116,
        120,  15,  15, 133,  64,  72,  35,  97,  23,  28]),
 array([135,  54, 108,  87,  12,  28,  13, 107,  14,  16, 137,  66,  41,
        100,  40,  45,  62, 128,  26,  83,  99,  99,  13,  80, 137,  82,
        112,  48,  54,  33, 104,  74,   1,  42,  90,  93,  62, 106,  94,
         18,  92,  60,  83,  94, 114,  63,   8, 128,   5,  44,  67,  51,
        101,  88,  93,  76,   2,  12,  50,  94,  14, 105,  49, 115,  69,
         61, 136,  83,  80, 110,  37, 101,  49,  55, 110,  59,  84,  23,
        105,  38,  48,  76, 134,  14,  99,  63,  29,  96, 117,  41,   2,
         95,  83,  71,   7,  28, 120,   4, 114, 113, 101, 102,  57,  66,
         75, 116,  51,  71,  40, 119, 122, 137,  14,  43, 111,  93,  15,
         54, 139,  37,  85,  42,  73, 107,  91, 108,  35, 124, 108,  85,
        116,  26, 109,  80,   2,  78,  51,   5,  31, 127]),
 array([126,  96, 105, 118, 123, 127, 133, 102,  68,  30,  87,  12,  69,
         56,   0,  34,  36,  38, 127, 118,  59, 110,   5,  15,  87,  94,
          9,  82,  64, 128, 113, 122,  17, 100,  20,  26, 123,  92,  38,
         62,  90,  48,  55,  82,  56,   5,   2,  33,  69, 131, 101,  75,
         20,  26,  46,  29,  96, 130,  72,  47,  29,  29,  95,  28,  64,
         22,  89,  13, 124, 100, 128, 129, 110, 123,  90, 136, 104, 128,
         28, 123,  65,  99,  63, 102, 120,  15,  51,  91,  88, 123,  10,
        124,  85,  18,  16,  47,  25,  37,  21,  85,  38,  56,  76, 139,
          2,  30,  76,  14,   1, 123,  60,  90, 115,   6,  45,  74,  67,
          6,  92,  10,   7,  83,  87,  24, 122, 122,  82,  66, 127,  58,
        136,  74,   4,  93,  17, 130, 110,  79, 116, 107]),
 array([ 23,  21,  43,  88, 112,   8, 109,  76,  68,  88,  64,  15, 132,
         56,  74,  13,  34,  17, 108,  49,  14, 134, 138,  55,  32,  55,
          1,  28,  99,  13,  34,  71, 116,  72,  55,   1,  73, 131,  36,
         67,  88, 127,  32, 123,   3,  92, 100,  47, 108, 121, 128, 105,
         68,  22,   0, 123, 120,  50,  50,  57, 121,  92,  20,   1,   3,
         96,  78,   1, 114,  71,  31,  35, 121,  67, 111, 127,  86,  86,
         60,  24,  87,  84,  31, 137, 130, 100,  68, 120, 136,  25,  16,
         10,  86, 106,  68, 126, 114, 135,  42,  69,  80, 100,  69,  46,
         81,  36,  19,  90,  34,   5,  13,  99,  77,  69,  75,  96,  16,
         34,  56,  66,  56, 115,  74,  66,  63,  99,  58,  69,  79,  99,
        102,  71,  30, 103,   4,  70,  25,  24,  90,  70]),
 array([ 98, 122,  63,  19,  94,   8,  10,  68, 106,  35,  33,  43,  31,
         97,  50,  61, 117,  50,   3, 102,  72,  70,  82, 137,   7,  82,
         20, 129,  16,  70,   1, 119,  25,  47,  51, 116,  11,  34,  58,
         43,  84, 115,  27,  32,  83,   9,  72,   1,  84,  13,  22,  90,
         99,  19, 110,  42,  57,  48,  64,  70, 134,  93, 130,  23, 102,
         79,  19,   7, 139,   2, 139,  95, 113,  89, 103,  83,  42,  40,
         90,  77,  31,  90,  32,  39,   1,  65, 135,  54,  91,  24,  55,
         24,  74,  76, 111,  58, 133, 109, 137, 124, 126, 103,   5, 112,
        128,  32, 128,  10, 117,  76,  62, 130,  88, 112,  52, 117,  41,
         86, 123,  51,  71,  71, 124, 127,  98,  12, 120,  41,  97,  44,
         40,  28, 117, 131,  77, 113,  39,  76,  39,  45]),
 array([ 28,  48, 109, 126, 110,  91, 134,  74,  48,  53,  60, 105,  69,
         15, 130,  31,  75,  41,  70,  83, 132,  79,  92,  53,   9,  16,
         14,  94,  94,  67, 100,  24,  41,  47, 127, 110,  31, 123,  92,
        119, 136, 128, 126,  76,   1,  65,  88, 125,  68, 121,   7, 105,
         15, 106,  95,  64, 103, 104,  74,  78,  57, 126,  61, 137,  26,
         75,  15,  98,  83, 124,  16, 123, 126,  85,  57,   8,  80, 129,
         51,  14,   2, 129,  59,  70,  15,  14,  27,  64, 107,  87,  50,
        124,  14,  82,  12, 103,  18,   8,  96, 125,  54,  45, 132, 122,
         54,  16, 102,  80,  43,  63,  72,  47,  61,  67,  51,   1,  92,
         75,  16,  91,  79,  50,  71,  68,  38,  82,  31,  15,   9,  12,
          1,  26,  60,  99,  18,  33,  80,  65,  80,  97]),
 array([ 68,  38,  18,  32, 120,  18,   6, 115,  16,  44,  60,  87,  22,
         43,  71,  66,  92, 131,  82, 127, 122,  70,  31,  72,  26,  20,
          5,   6,  67,  58, 108, 139,  31,  53,  11,  85,  83,  21,   6,
        131,   3,  95, 103,  82, 108,  21,  19, 129,  93,  44,  15,  61,
         19,  37,  12, 125,  26, 115,  28,  56, 105, 109,  79,  47,  39,
         69,  26,   4,  74,  30,  75,  69, 110,  71,  43,  92,  71, 112,
         59,  91,  69,  20,  14,  87,  34,  18,  71, 106,  98, 103,  56,
         49,  30,  74,  95,  32,  23,  31,  51, 129,  24,  21, 134, 103,
        111,  57, 108,  23, 118,  67,  34, 138, 120,   2,  10,  77,  66,
         95, 105, 139,  11,  64,  68, 139,  53, 128,  33,  95,  83,  76,
         83,  38, 108,  90, 110,   6, 127,  32,  19, 101]),
 array([ 68,   8,  43,  25,  56,   2, 119,  10,  82,   4,  38, 136, 113,
         39,   8, 121,  85, 131,  71, 123,  98, 127,  61, 136,  20, 135,
          3,  17, 117, 103, 113, 102,  92, 127,   8,   6,  26, 120, 105,
         25,  26,  20,  42,  31,  80, 113, 134,  60,  88,  21,  22, 125,
         38,  82, 134, 108,  98,  31,   8, 118,  48,  72,  15, 130, 123,
        119,  10,  58,  66,  84,  97, 129,  10,  55,  62,  38,  88,  28,
         87,  36, 119, 107, 101,  28,  35, 134, 124,   8,  56, 137,  81,
        129, 111,  53,  29, 136, 100,  15,   1,  34,  56,  75, 116,   7,
         56, 104,  14,  33, 138,  19, 106,  92, 135, 125,  67,  64,   4,
        114,  45,  81, 127, 133,  64,  21, 136,  92, 109,  57,  65,  34,
         19, 119, 135,  89,  74,   1,  70,  91,  60,  28])]

In [47]:
Bag.estimators_features_

[array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6])]

We see the training accuracy is slightly better but the test accuracy improves dramatically:

In [78]:
print(get_accuracy(X_train, X_test, y_train, y_test,  Bag))

{'test Accuracy': 0.975609756097561, 'train Accuracy': 0.9853556485355649}

Each tree is similar; we can see this by plotting the correlation between each tree and the average correlation.

In [40]:
get_correlation(X_test, y_test,Bag).style.background_gradient(cmap='coolwarm')

Average correlation between predictors:  0.22981703902385342

It can be shown that this correlation reduces performance. Random forest minimizes the correlation between trees, improving results.

## Random  Forest

Random forests are a combination of trees such that each tree depends on a random subset of the features and data. As a result, each tree in the forest is different and usually performs better than Bagging. The most important parameters are the number of trees and the number of features to sample. First, we import <code>RandomForestClassifier</code>.

In [41]:
from sklearn.ensemble import RandomForestClassifier

Like Bagging, increasing the number of trees improves results and does not lead to overfitting in most cases; but the improvements plateau as you add more trees. For this exxample, the number of trees in the forest (default=100):

In [48]:
n_estimators=20

<code>max_features </code>   $m$ the number of features to consider when looking for the best split. If we have M features denoted by:

In [49]:
M_features=X.shape[1]

If we have M features, a popular method to determine m is to use the square root of M

$m= floor(\sqrt{M}) $

In [50]:
max_features=round(np.sqrt(M_features))-1
max_features

2

In [51]:
y_test

58     1
40     0
34     0
102    0
184    0
198    1
95     1
4      0
29     0
168    0
171    1
18     0
11     0
89     0
110    0
118    0
159    1
35     0
136    1
59     0
51     0
16     0
44     0
94     0
31     0
162    0
38     0
28     0
193    0
27     0
47     0
165    0
194    0
177    0
176    0
97     1
174    1
73     0
69     0
172    1
108    0
107    1
189    0
14     0
56     0
19     1
114    0
39     0
185    0
124    0
98     0
123    1
119    0
53     0
33     1
179    0
181    0
106    0
199    0
138    1
Name: churn, dtype: int64

We use floor to make sure $m$ is an integer:

We create the RF object :

In [52]:
model = RandomForestClassifier( max_features=max_features,n_estimators=n_estimators, random_state=0)

We train the model

In [53]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=2, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

We obtain the training and testing accuracy; we see that RF does better than Bagging:

In [54]:
print(get_accuracy(X_train, X_test, y_train, y_test, model))

{'test Accuracy': 0.8, 'trian Accuracy': 0.9857142857142858}

We see that each tree in RF is less correlated than Bagging:

In [55]:
get_correlation(X_test, y_test,model).style.background_gradient(cmap='coolwarm')

Average correlation between predictors:  0.2133517931899367

<h2 id="Example">Cancer Data Example</h2>

The example is based on a dataset that is publicly available from the UCI Machine Learning Repository (Asuncion and Newman, 2007)\[[http://mlearn.ics.uci.edu/MLRepository.html](http://mlearn.ics.uci.edu/MLRepository.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML241ENSkillsNetwork31576874-2022-01-01)]. The dataset consists of several hundred human cell sample records, each of which contains the values of a set of cell characteristics. The fields in each record are:

| Field name  | Description                 |
| ----------- | --------------------------- |
| ID          | Clump thickness             |
| Clump       | Clump thickness             |
| UnifSize    | Uniformity of cell size     |
| UnifShape   | Uniformity of cell shape    |
| MargAdh     | Marginal adhesion           |
| SingEpiSize | Single epithelial cell size |
| BareNuc     | Bare nuclei                 |
| BlandChrom  | Bland chromatin             |
| NormNucl    | Normal nucleoli             |
| Mit         | Mitoses                     |
| Class       | Benign or malignant         |

<br>
<br>

Let's load the dataset:

In [56]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/cell_samples.csv")

df.head()

,ID,Clump,UnifSize,UnifShape,MargAdh,SingEpiSize,BareNuc,BlandChrom,NormNucl,Mit,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

Now lets remove rows that have a ? in the <code>BareNuc</code> column:

In [57]:
df= df[pd.to_numeric(df['BareNuc'], errors='coerce').notnull()]

We obtain the features:

In [58]:
X =  df[['Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize', 'BareNuc', 'BlandChrom', 'NormNucl', 'Mit']]

X.head()

,Clump,UnifSize,UnifShape,MargAdh,SingEpiSize,BareNuc,BlandChrom,NormNucl,Mit
0,5,1,1,1,2,1,3,1,1
1,5,4,4,5,7,10,3,2,1
2,3,1,1,1,2,2,3,1,1
3,6,8,8,1,3,4,3,7,1
4,4,1,1,3,2,1,3,1,1

We obtain the class labels:

In [59]:
y=df['Class']
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

We split the data into training and testing sets.

In [60]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (546, 9) (546,)
Test set: (137, 9) (137,)

We use <code>GridSearchCV</code> to search over specified parameter values  of the model.

In [61]:
from sklearn.model_selection import GridSearchCV

We create a <code>RandomForestClassifier</code> object and list the parameters using the method <code>get_params()</code>:

In [62]:
model = RandomForestClassifier()
model.get_params().keys()

dict_keys(['bootstrap', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_impurity_split', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'n_estimators', 'n_jobs', 'oob_score', 'random_state', 'verbose', 'warm_start'])

In [63]:
model.get_params()

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 'warn',
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

We can use GridSearch for Exhaustive search over specified parameter values. We see many of the parameters are similar to Classification trees; let's try a different parameter for <code>max_depth</code>, <code>max_features</code> and <code>n_estimators</code>.

In [64]:
param_grid = {'n_estimators': [2*n+1 for n in range(20)],
             'max_depth' : [2*n+1 for n in range(10) ],
             'max_features':["auto", "sqrt", "log2"]}

We create the Grid Search object and fit it:

In [65]:
search = GridSearchCV(estimator=model, param_grid=param_grid,scoring='accuracy')
search.fit(X_train, y_train)

GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39], 'max_depth': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 'max_features': ['auto', 'sqrt', 'log2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

We can see the best accuracy score of the searched parameters was \~97%.

In [66]:
search.best_score_

0.9798534798534798

The best parameter values are:

In [67]:
search.best_params_

{'max_depth': 3, 'max_features': 'log2', 'n_estimators': 25}

We can calculate accuracy on the test data using the test data:

In [73]:
print(get_accuracy(X_train, X_test, y_train, y_test, search.best_estimator_))

{'test Accuracy': 0.9708029197080292, 'train Accuracy': 0.9816849816849816}

<h2 id="practice">Practice</h2>

Imagine that you are a medical researcher compiling data for a study. You have collected data about a set of patients, all of whom suffered from the same illness. During their course of treatment, each patient responded to one of 5 medications, Drug A, Drug B, Drug c, Drug x and y.

Part of your job is to build a model to find out which drug might be appropriate for a future patient with the same illness. The features of this dataset are Age, Sex, Blood Pressure, and the Cholesterol of the patients, and the target is the drug that each patient responded to.

It is a sample of multiclass classifier, and you can use the training part of the dataset to build a decision tree, and then use it to predict the class of a unknown patient, or to prescribe a drug to a new patient.

In [70]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv", delimiter=",")
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

Let's create the X and y for our dataset:

In [79]:
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [80]:
y = df["Drug"]
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

Now lets use a <code>LabelEncoder</code> to turn categorical features into numerical:

In [81]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3]) 

X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

Split the data into training and testing data with a 80/20 split

In [82]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 5) (160,)
Test set: (40, 5) (40,)

We can use GridSearch for Exhaustive search over specified parameter values.

In [83]:
param_grid = {'n_estimators': [2*n+1 for n in range(20)],
             'max_depth' : [2*n+1 for n in range(10) ],
             'max_features':["auto", "sqrt", "log2"]}

Create a <code>RandomForestClassifier </code>object called <cood>model</code> :

In [84]:
model = RandomForestClassifier()

<details><summary>Click here for the solution</summary>

```python
model = RandomForestClassifier()

```

</details>

Create <code>GridSearchCV</code> object called `search` with the `estimator` set to <code>model</code>, <code>param_grid</code> set to <code>param_grid</code>, <code>scoring</code> set to <code>accuracy</code>, and  <code>cv</code> set to 3 and Fit the <code>GridSearchCV</code> object to our <code>X_train</code> and <code>y_train</code> data

In [85]:
search = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=3)
search.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39], 'max_depth': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 'max_features': ['auto', 'sqrt', 'log2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

<details><summary>Click here for the solution</summary>

```python
search = GridSearchCV(estimator=model, param_grid=param_grid,scoring='accuracy', cv=3)
search.fit(X_train, y_train)

```

</details>

We can find the accuracy of the best model.

In [86]:
search.best_score_

1.0

We can find the best parameter values:

In [87]:
search.best_params_

{'max_depth': 11, 'max_features': 'log2', 'n_estimators': 13}

We can find the accuracy test data:

In [88]:
print(get_accuracy(X_train, X_test, y_train, y_test, search.best_estimator_))

{'test Accuracy': 0.925, 'train Accuracy': 1.0}

<details><summary>Click here for the solution</summary>

```python
print(get_accuracy(X_train, X_test, y_train, y_test, search.best_estimator_))
```

</details>

<h2>Want to learn more?</h2>

IBM SPSS Modeler is a comprehensive analytics platform that has many machine learning algorithms. It has been designed to bring predictive intelligence to decisions made by individuals, by groups, by systems – by your enterprise as a whole. A free trial is available through this course, available here: <a href="https://www.ibm.com/analytics/spss-statistics-software?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2021-01-01">SPSS Modeler</a>

Also, you can use Watson Studio to run these notebooks faster with bigger datasets. Watson Studio is IBM's leading cloud solution for data scientists, built by data scientists. With Jupyter notebooks, RStudio, Apache Spark and popular libraries pre-packaged in the cloud, Watson Studio enables data scientists to collaborate on their projects without having to install anything. Join the fast-growing community of Watson Studio users today with a free account at <a href="https://www.ibm.com/cloud/watson-studio?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2021-01-01">Watson Studio</a>

### Thank you for completing this lab!

## Author

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2021-01-01" target="_blank">Joseph Santarcangelo</a>

### Other Contributors

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By           | Change Description   |
| ----------------- | ------- | -------------------- | -------------------- |
| 2022-02-09        | 0.1     | Joseph Santarcangelo | Created Lab Template |
| 2022-05-03        | 0.2     | Richard Ye           | QA pass              |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>